# Makefile pour le projet SI3 -- Serveur Web (tests)
#
#          Author: Erick Gallesio [eg@unice.fr]
#    Creation date: 22-Apr-2013 12:19 (eg)
# Last file update:  1-Jun-2013 22:40 (eg)


all:
	@echo "nothing to do in this directory"

clean:
	/bin/rm -f  Dir*/*~  *~

clobber: clean

